# Organize

The first step in data preparation is simply about organizing the raw data files so that we can more easily merge the data files using E-Merge.

Initially the data files are stored on separate computers along with the task program and stimulus materials. For each task we need to grab only the data files from each computer and put them into a single folder for that task.

**Because we have many tasks and computers, manually doing this can be quite tedious and error prone.**

I have created R scripts that you can run on each running room computer to copy the data files for each task to the Z drive.

----

1. Connect the computer to the **internet**

    Do this by plugging in the yellow ethernet cord

2. Connect to the **Z Drive**

    There should be a shortcut to a Z: Drive folder on the Desktop. If you can open that shortcut then the Z Drive is connected. Otherwise it might prompt you to provide credentials. A Grad Student or Post-Doc will have to put in their GT username and password.

3. **Run** the R script. In the study folder on the Desktop there should be an R script file (copy_to_zdrive.R). Run the file by double-clicking on it. 

    A command prompt window should open up and you should see the output of the script being printed. When the R script is finished running (it may take a while especially for eye-tracking data) the command prompt window will close.
    
4. **Unplug** the computer from the internet

5. **Repeat** steps 1-4 for each running room computer.

