# Export

The third step in the data preparation stage is to **Export** the **.emrg** to a **.txt** file so it can be imported into R. 

Before we can do so we will need to copy the E-Prime merged files from the Z: drive over to SharePoint. *This is only because exporting the files takes considerably longer on the Z: drive than SharePoint*.


1. **Copy** all the E-Prime Merged data files over to SharePoint:

    Georgia Institute of Technology / Engle Lab - Documents / Data Collection / [Study Name] / **Data Files / <span style="color: FireBrick">Merged</span>**

2. **Open** an E-Merged data file

3. Go to File **<span style="color: FireBrick"> -> </span>** Export...

4. Change the following options

    **Unicode**: Uncheck
    
5. Select **Okay**

6. **Save** with the same file name and location as the E-Merge file

    **Data Files / <span style="color: FireBrick">Merged</span>**
    
    If there is already an exported .txt file for this task then overwrite it.
    
7. **Repeat** steps 2 - 6 for each task


