# Source R Scripts

----

The Four Data Preparation Steps

1. **Organize the raw data files**. This involves moving the raw *.edat* files from *Tasks/Session #/#. Task/data* to *Data Files/edat/Task/*.

2. **Merge** the individual *.edat* files into a single **task.emrg** file using *E-Merge*

3. **Export** the **task.emrg** file to a **task.txt** file so we can process the data in **R**

4. **Source** the **0_task_raw.R** *Scripts* 

----

The final data preparation step is to **Source** the **0_task_raw.R** scripts. These scripts convert the messy **task.txt** files to tidy **task_raw.csv** files. 

## Steps

The masterscript should be created already, if not then get a graduate student to help out (Jason Tsukahara)

1. Open the research study's RProject file (**.Rproj**) located at:

    **Dropbox (GaTech) / EngleLab / Studies / [StudyName] / [StudyName].Rproj**

    Do not open RStudio by clicking on the Program Application in the taskbar
    
2. Open the file **masterscript.R**

    **Use the File Window pane in RStudio (in the bottom right corner to open script files)**
    
3. Run the lines of code in the masterscript that start with `source()` by clicking anywhere on the first line of code and press Ctrl+Enter

4. Make sure no error messages occur (these will be printed in the console window). Warning messages are okay. The Environment window should also say "Environment is empty"

5. Repeat Steps 3 and 4 for each `source()` line of code.

There should now be a **_raw.csv** file for each task located in the **Data Files** folder

