# Tidy

The final data preparation step is to **tidy** the raw data files by sourcing the **task_raw.R** scripts. These scripts convert the messy **task.txt** files to tidy **task_raw.csv** files. 

*A masterscript for this step should be created already, if not then get a graduate student to help out (Jason Tsukahara)*

1. **Open** the research study's RProject file (**.Rproj**) located at:

    Georgia Institute of Technology / Engle Lab - Documents / **Data Collection / [Study Name] / [StudyName].Rproj**

    *Do not open RStudio by clicking on the Program Application in the taskbar*
    
2. Open the file **masterscript.R**

    *Use the File Window pane in RStudio (in the bottom right quadrant) to find the masterscript file*
    
3. **Run** the lines of code in the masterscript that start with `source()` by clicking anywhere on the first line of code and press **Ctrl+Enter**

4. **Make sure no error messages occur** (these will be printed in the console window). Warning messages are okay.

5. **Repeat** Steps 3 and 4 for each `source()` line of code.

There should now be a **\_raw.csv** file for each task located in the **Data Files** folder

