# Pupil Data

There are a few extra **Data Preparation** steps required for pupil data.

The eyetracker will create several data files that we need to import into BeGaze analysis software and export as a .txt file. The following data files are created by the eyetracker 

- **.idf** - this file contains the actual gaze and pupil data

- **AccuracyImage.bmp** - An image file

- **TrackingMonitorImage.bmp** - An image file

- **.idf_images** - These files will look like folders. *We do not need to import these files*

In Step 1 of Data Preparation these files were added to the Z Drive: **Z:/Backup Data/[STUDY NAME]/Subject Files/[Task Name]/<span style="color: FireBrick">idf</span>**

## Copy from Z Drive to the Yellow Hard Drive

1. Copy the files from the Z Drive to the Yellow Hard Drive

    **Z:/Backup Data/[STUDY NAME]/Subject Files/[Task Name]/<span style="color: FireBrick">idf</span>**
    
    **PupilBackup (G:)/[STUDY NAME]/[Task Name]/<span style="color: FireBrick">idf</span>**

## BeGaze

1. **Open** data files in BeGaze

    - File **<span style="color: FireBrick"> -> </span>** Manual Experiment Creation
    
    - Experiment Name: **PupilData**
    
    - Go to the **Gaze Data** tab:
    
        - Navigate to **PupilBackup (G:)/[STUDY NAME]/[Task Name]/<span style="color: FireBrick">idf</span>**
    
        - Sort by Data **<span style="color: FireBrick"> -> </span>** select the **<span style="color: FireBrick"> .idf files </span>** you want (not .idf_images) **<span style="color: FireBrick"> -> </span>** Open
        
        - Check if any subject files have a different recording frequency (Hz) or different calibration screen resolution (e.g. [860,720])
        
        -Select those subject files and click “Remove Files”
        
        - On the computer in the **idf** folder, move all the files associated with those subjects to a “recording error” folder: **PupilBackup (G:)/[STUDY NAME]/[Task Name]/idf/<span style="color: FireBrick">recording error</span>** 
        
        - Check that all subjects have the same recording frequency (Hz) and calibration screen resolution.


    - Go to **Stimulus Images** tab:
    
        - Add Files… **<span style="color: FireBrick"> -> </span>** Sort by Date **<span style="color: FireBrick"> -> </span>** select the **<span style="color: FireBrick"> AccuracyImage.bmp </span>** and **<span style="color: FireBrick"> TrackingMonitorIMage.bmp </span>** files you want (not .idf_images)


    - Go to **Event Detection** tab:
    
        - Set Event Detection to: **High Speed**
        
        - Set the following parameters:
        
            - 22
            
            - 40%
            
            - 50 ms
            
            - 20%
            
            - 80%
            
    - Select **Create Experiment**

<br>
    
2. **Convert** .idf files to .txt files

    - Export **<span style="color: FireBrick"> -> </span>** Legacy: Export Raw Data to File...
    
    - The following fields should be selected (Fields with an __\*__ are the most important)
    
        **Raw Data**:
        
        - Pupil Diameter
        
        - Pupil Diameter [mm] __\*__ 
        
        **Channel**:
        
        - Left Eye __\*__
        
        - Right Eye __\*__
        
        **Points of Regard (POR)**:
        
        - Gaze Position __\*__
        
        - Quality Values
        
        - Eye Position
        
        - Gaze Vector
        
        **Misc. Data**:
        
        - Messages __\*__
        
        - Event Info __\*__
        
        - Stimulus
        
        - Stimulus Conditions
        
    - Select **Details** tab
    
        - Select **Write header**
        
        - Decimal places: **4**
        
        - Separator: **Tab**
        
        - Export Location:  **<span style="color: FireBrick"> NEEDS TO BE SPECIFIED!! </span>**
        
            - Browse: **PupilBackup (G:)/[STUDY NAME]/<span style="color: FireBrick">[Task Name]</span>**
            
        - Select **Single file output**
        
    - Select **Export**
    
    - Go to File **<span style="color: FireBrick"> -> </span>** **Close Experiment**
    
    - Got to File **<span style="color: FireBrick"> -> </span>** **Delete Experiment from Data Base**
    
    - **Delete** PupilData Experiment
    
3. **Repeat** steps 1 - 2 for each eye-tracking task

