--- 
title: "EngleLab: Data Preparation"
author: "Jason Tsukahara"
bibliography:
- book.bib
- packages.bib
description: This is a useR Guide for the EngleLab
documentclass: book
link-citations: yes
site: bookdown::bookdown_site
biblio-style: apalike
github-repo: "EngleLab"
---

# Introduction {-}

At some point you will need to start analyzing the data. However, you first need to prepare the data so that it is ready to analyze. There are several steps in this processs and it can be quite tedious.

There are two scenarios in which you may need to start processing and analyzing data:

- Before data collection has finished

- After data collection has finished

<br>

For both of these scenarios, there are **4 data preparation steps:**

1. **Organize the raw data files**. This involves moving the raw *.edat* files from *Tasks/Session #/#. Task/data* to *Data Files/edat/Task/*.

2. **Merge** the individual *.edat* files into a single **task.emrg** file using *E-Merge*

3. **Export** the **task.emrg** file to a **task.txt** file so we can process the data in **R**

4. **Source** the **0_task_raw.R** *Scripts* 

After performing the 4 data preparation steps you will have *tidy* raw data files for each task saved as **task_raw.csv** in the *Data Files* folder. It is these files that you can then copy over to a *Data Analysis* repository.

To understand more about Project Organization and the different types of repositories, see [**Chapter 7**](http://englelab.gatech.edu/userguide/project-organization.html) in the **UseR Guide**.


